openapi: 3.0.3
info:
  title: Fishing Competition API
  version: 0.0.1
  description: API for managing fishing competitions

paths:
  /competitors:
    get:
      operationId: getCompetitors
      summary: List all competitors
      responses:
        '200':
          description: List of competitors
    post:
      operationId: createCompetitor
      summary: Create a competitor
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Competitor'
      responses:
        '201':
          description: Created
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /competitors/{id}:
    get:
      operationId: getCompetitor
      summary: Get a competitor by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Competitor details
        '404':
          description: Competitor not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      operationId: updateCompetitor
      summary: Update a competitor
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Updated
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Competitor not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      operationId: deleteCompetitor
      summary: Delete a competitor
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
        '404':
          description: Competitor not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      type: object
      description: Error response
      properties:
        error:
          type: string
          description: Error message
      required:
        - error

    Competitor:
      type: object
      description: A competitor in the fishing competition
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the competitor
        first_name:
          type: string
          description: First name of the competitor
        last_name:
          type: string
          description: Last name of the competitor

