
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package model


import (
	
	"context"
	
	
	
	
)






const getCompetitors = `-- name: GetCompetitors :many
select id, competitor_no, firstname, last_name, email, mobile, phone, address1, address2, suburb, state, postcode, boat_id
from competitor
`








func (q *Queries) GetCompetitors(ctx context.Context,  ) ([]Competitor, error) {rows, err := q.db.QueryContext(ctx, getCompetitors, )
    if err != nil {
        return nil, err
    }
    defer rows.Close()
    var items []Competitor
    for rows.Next() {
        var i Competitor
        if err := rows.Scan(
&i.ID,
&i.CompetitorNo,
&i.Firstname,
&i.LastName,
&i.Email,
&i.Mobile,
&i.Phone,
&i.Address1,
&i.Address2,
&i.Suburb,
&i.State,
&i.Postcode,
&i.BoatID,
); err != nil {
            return nil, err
        }
        items = append(items, i)
    }
    if err := rows.Close(); err != nil {
        return nil, err
    }
    if err := rows.Err(); err != nil {
        return nil, err
    }
    return items, nil
}















